parameters:
    mapacomedoressociales.map.populate.repository_class: 'MapaComedoresSociales\PantryBundle\Entity\Pantry'

services:
    mapacomedoressociales.form.type.pantry_type:
        class: MapaComedoresSociales\PantryBundle\Form\PantryType
        tags:
            - { name: form.type, alias: pantryType }

    mapacomedoressociales.form.flow.pantry_type_flow:
        class: MapaComedoresSociales\PantryBundle\Form\PantryTypeFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ @mapacomedoressociales.form.type.pantry_type ] ]
            - [ setGeocoder, [ @ivory_google_map.geocoder= ] ]

    mapacomedoressociales.manager.map:
        class: MapaComedoresSociales\PantryBundle\Model\MapManager
        scope: prototype
        arguments:
            - @doctrine.orm.entity_manager
            - @ivory_google_map.map
            - @ivory_google_map.pan_control
            - @ivory_google_map.map_type_control
            - %mapacomedoressociales.map.populate.repository_class%
