services:
    mapa_comedores_sociales.frontend_bundle.menu.main.builder:
        class: MapaComedoresSociales\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    mapa_comedores_sociales.frontend_bundle.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: mapa_comedores_sociales.frontend_bundle.menu.main.builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu