imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: /usr/bin/java
    read_from:        %kernel.root_dir%/../web
    write_to:         %kernel.root_dir%/../web
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssembed:
             jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    navbar: ~


# Doctrine Extensions Configuration
stof_doctrine_extensions:
        default_locale: es_ES
        translation_fallback: true
        orm:
            default:
              timestampable: true
              tree: true
              
ivory_google_map:
    map:
        # If this flag is enabled, the map will load asynchronous
        async: true

        # If this flag is enabled, the map will autozoom on the overlays added
        #auto_zoom: true

        # Center coordinate of the map
        # If the autozoom flag is enabled, the center is not used
        center:
            longitude: 2.1676915
            latitude: 41.3809434
            no_wrap: true

        # Zoom of the map
        # If the autozoom flag is enabled, the zoom is not used
        zoom: 13

        # Default map type
        # Available map type : hybrid, roadmap, satellite, terrain
        type: "roadmap"

        # Map width
        width: "900px"

        # Map height
        height: "400px"

        # Custom map options
        # By default, there is no map options
        map_options:
            disableDefaultUI: true
            disableDoubleClickZoom: true

        # Custom stylesheet options
        # By default, there is no stylesheet options except width & height
        stylesheet_options:
            border: "1px solid #000"
            background-color: "#fff"

        # google map Api language, default en
        language: es