frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /comment

geo_location:
    resource: "@GeoLocationBundle/Resources/config/routing.yml"
    prefix:   /geo

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

pantry:
    resource: "@PantryBundle/Resources/config/routing.yml"
    prefix:   /pantry

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

_welcome:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index }
