frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /comment

geo_location:
    resource: "@GeoLocationBundle/Controller/"
    type:     annotation
    prefix:   /geo

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

pantry:
    resource: "@PantryBundle/Controller/"
    type:     annotation
    prefix:   /pantry

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

_welcome:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
