frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /comment

geo_location:
    resource: "@GeoLocationBundle/Resources/config/routing.yml"
    prefix:   /geo

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

pantry:
    resource: "@PantryBundle/Resources/config/routing.yml"
    prefix:   /pantry

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_welcome:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index }
