comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

geo_location:
    resource: "@GeoLocationBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

pantry:
    resource: "@PantryBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern: /
    defaults: { _controller: FrontMainBundle:Main:index }

front_main:
    resource: "@FrontMainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
