security:
    encoders:
        MapaComedoresSociales\UserBundle\Entity\User: plaintext #Cambiar mas adelante por sha512

    providers:
        users:
            entity: { class: UserBundle:User, property: email }

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            http_basic: ~
            form_login: 
                login_path: user_login
                check_path: user_login_check

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USER }
