security:
    encoders:
        MapaComedoresSociales\UserBundle\Entity\User:
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1

    providers:
        users:
            entity: { class: UserBundle:User, property: email }


    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            http_basic: ~
            form_login: 
                login_path: user_login
                check_path: user_login_check
            remember_me:
                key: "5445ASDASD" # "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USER }
