security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
#        MapaComedoresSociales\UserBundle\Entity\User:
#            algorithm:          sha1
#            encode_as_base64:   false
#            iterations:         1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
#        frontend:
#            pattern: ^/*
#            anonymous: ~
#            http_basic: ~
#            form_login: 
#                login_path: user_login
#                check_path: user_login_check
#            logout:
#                path: user_logout
#                target: _welcome
#            remember_me:
#                key: "5445ASDASD" # "%secret%"
#                lifetime: 31536000 # 365 days in seconds
#                path: /.*
#                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        - { path: ^/user/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USER }
        
