UserBundle_user:
   resource: "@UserBundle/Resources/config/routing/user.yml"
   prefix: /

user_login:
   pattern: /login
   defaults: { _controller: "UserBundle:Default:login" }

user_login_check:
   pattern: /login_check

user_logout:
   pattern: /logout

user_register:
   pattern: /register
   defaults: { _controller: "UserBundle:Default:register" }

user_remember:
    pattern: /remember
    defaults: { _controller: "UserBundle:Default:rememberPassword" }

user_change:
    pattern: /change_password
    defaults: { _controller: "UserBundle:Default:changePassword" }