<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130302150707 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->write('@author: mgonyan');
        $this->write('Pantry Types');

        $this->addSql("insert into `Type` (`id`, `name`, `description` ) values('1','pantry', 'Social Pantry')");
        $this->addSql("insert into `Type` (`id`, `name`, `description` ) values('2', 'collect', 'Collect Food')");
    }

    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("delete from `Type` where id = 'pantry'");
        $this->addSql("delete from `Type` where id = 'collect'");
    }
}
