services:

services:
    front.main_bundle.menu.main.builder:
        class: Front\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    front.main_bundle.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: front.main_bundle.menu.main.builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
            